### ISSUE TITLE
fix error with 'config' variable

### ISSUE THREAD

**Issue by vanzhiganov** [penkins/penkins_ci#9]
when I ran `/usr/bin/python /var/lib/penkins/penkins.py` then I see:

```
Traceback (most recent call last):
  File "/var/lib/penkins/penkins.py", line 115, in <module>
    config = PenkinsConfig('.penkins.yaml')
  File "/var/lib/penkins/penkins/__init__.py", line 10, in __init__
    self.config = self.__read(file_name)
  File "/var/lib/penkins/penkins/__init__.py", line 15, in __read
    return config
UnboundLocalError: local variable 'config' referenced before assignment
```

need to change `config` to `penkins_config`

**Comment by vanzhiganov** [comment]
may not have a permission to log file writing in /var/log
